// src/components/ui/layout/Header.tsx
import { useState } from 'react'
import classNames from 'classnames'
import Link from 'next/link'
import Navigation from '@/components/ui/layout/Navigation'
type TypeProps = {
	className?: string
}

const Header = ({ className }: TypeProps) => {
	const [open, setOpen] = useState(false)
	/**
	 * ナビ開閉
	 */
	const toggleOpen = () => {
		setOpen(!open)
	}
	/**
	 * ナビを閉じる
	 */
	const close = () => {
		setOpen(false)
	}

	const CloseButton = () => {
		return (
			<button
				className={`flex justify-between items-center w-14 h-14 mt-auto ml-auto px-2 leading-none font-semibold text-accent`}
				onClick={close}
				type="button"
			>
				<span>&lt;</span>
				<span>/</span>
				<span>&gt;</span>
			</button>
		)
	}
	return (
		<>
			<header
				className={classNames([
					'fixed top-0 right-0 left-0 z-30',
					'flex justify-start',
					'py-3 px-4 md:px-6 lg:px-8',
					'!border-0',
					'gradation-dark',
					className,
				])}
			>
				<p className="self-center w-8 md:w-10 lg:w-14">
					<Link href="/">
						<a className="grid place-items-center bg-white rounded-full p-1 lg:p-2 leading-none transition-opacity hover:opacity-80">
							<img
								src="/logo/icon_fill.svg"
								alt="しゃもキット"
								width={40}
								height={40}
								className="object-contain"
								loading="lazy"
							/>
						</a>
					</Link>
				</p>
				<button
					className="absolute top-0 right-0 z-10 flex md:hidden flex-col justify-center items-center w-14 h-14 text-center leading-tight font-semibold overflow-hidden"
					onClick={toggleOpen}
					type="button"
				>
					<span
						className={`absolute inset-y-0 flex justify-between items-center w-full px-2 leading-none text-bold text-accent`}
					>
						<span
							className={`relative flex transition-transform ${
								open ? 'translate-x-0' : '-translate-x-full opacity-0'
							}`}
						>
							&lt;
						</span>
						<span
							className={`relative flex transition-transform ${
								open ? 'translate-x-0' : 'translate-x-full opacity-0'
							}`}
						>
							&gt;
						</span>
					</span>
					<span
						className={`block w-5 mb-0.5 border  transition-transform relative shadow-inner border-accent ${
							open ? 'rotate-45 top-[3px]' : 'rotate-0'
						}`}
					></span>
					<span
						className={`block w-5 mt-0.5 border  transition-transform relative shadow-inner border-accent ${
							open ? '-rotate-45 -top-[3px]' : 'rotate-0'
						}`}
					></span>
					<span className="sr-only">menu</span>
				</button>
				<Navigation open={open} closeButton={<CloseButton />} />
			</header>
			<div
				className={classNames([
					'fixed top-0 right-0 z-20',
					'md:hidden',
					'w-full h-screen',
					'transition-opacity bg-main-bg bg-opacity-20 backdrop-blur-sm',
					open ? 'opacity-100' : 'opacity-0 pointer-events-none',
				])}
				onClick={close}
			></div>
		</>
	)
}
export default Header

// src/lib/components/layouts/header/index.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Logo from '$lib/components/logo/index.svelte';
	import Navigation from '$lib/components/layouts/navigation/index.svelte';
	import { BREAK_POINTS } from '$lib/const';
	let windowWidth: number = 0;
	$: open = false;
	const closeMenu = () => {
		if (windowWidth < BREAK_POINTS.lg) {
			open = false
		}
	}
	onMount(() => {
		windowWidth = document.body.getBoundingClientRect().width
		if(windowWidth >= BREAK_POINTS.lg) {
			open = true
		} else {
			open = false
		}
		const resizeObserver = new ResizeObserver((entries) => {
			const entry = entries.at(0);
			if (!entry) return;
			windowWidth = entry.contentBoxSize[0].inlineSize;
			if (windowWidth >= BREAK_POINTS.lg) {
				if (!open) {
					open = true;
				}
			}
		});
		resizeObserver.observe(document.body);
		return () => resizeObserver.unobserve(document.body);
	});
</script>

<header
	class="fixed top-0 left-0 right-0 flex items-center h-[var(--header-height)] px-2 lg:px-10 bg-blend-overlay backdrop-blur-sm bg-surface-100"
>
	<h1 class="relative z-10">
		<a
			href="/"
			class="flex items-center gap-2 text-primary-500 text-sm lg:text-md transition-colors hover:text-accent-500"
			on:click={closeMenu}
		>
			<span class="block w-10 lg:w-14 shrink-0 p-1 lg:p-2"><Logo /></span>
			<span class="font-bold">しゃもきっとブログ</span>
		</a>
	</h1>
	<div class="ml-auto">
		<button
			type="button"
			class="absolute z-10 top-1/2 -translate-y-1/2 right-2 grid place-items-center grid-cols-[1fr_12px_1fr] grid-rows-[1fr_2px_1fr] rounded-full bg-surface-500 lg:hidden w-10 h-10 text-primary-500"
			on:click={() => (open = !open)}
			aria-expanded={open}
			aria-controls="globalNavigation"
			aria-label={open ? 'メニューを閉じる' : 'メニューを開く'}
		>
			<span
				class="flex col-[2_/_3] row-[2_/_3] w-3 border-b-2 border-current transition-all"
				class:translate-y-1={!open}
				class:rotate-45={open}
			/>
			<span
				class="flex col-[2_/_3] row-[2_/_3] w-3 border-b-2 border-current transition-all"
				class:opacity-0={open}
			/>
			<span
				class="flex col-[2_/_3] row-[2_/_3] w-3 border-b-2 border-current transition-all"
				class:-translate-y-1={!open}
				class:-rotate-45={open}
			/>
		</button>
		<Navigation
			class={`absolute lg:static top-0 left-0 right-0 max-h-screen overflow-auto overscroll-contain pt-[var(--header-height)] lg:pt-0 transition-opacity bg-surface-100 lg:bg-transparent ${
				open ? 'visible opacity-100' : 'invisible opacity-0'
			}`}
			open={open}
			on:menuClose={closeMenu}
		/>
	</div>
</header>
